### DISCUSSION TITLE
How to get external access to multiple shares?

### DISCUSSION THREAD

**Discussion by pfaelzerchen** [samba-in-kubernetes/samba-operator#348] [Q&A]
After getting rid of some problems with my storage provider, I wanted to give another try on the samba-operator. I tried to deploy two smbshares to the cluster. Everything seems fine at first. pods are coming up, svcs of type LoadBalancer are configured, ...  But when I open smb://host, I will only see the first of the two smbshares.

It is probably logical because there are several svcs trying to use the same external port 445. Is there a way to expose both shares at the same time?

```yaml
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
  name: smb-users
  namespace: media-files
spec:
  mode: user
  users:
    secret: smb-secrets
    key: smbusers
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
  name: smb-config
  namespace: media-files
spec:
  network:
    publish: external
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
  name: backup
  namespace: media-files
spec:
  securityConfig: smb-users
  commonConfig: smb-config
  browseable: true
  readOnly: false

  storage:
    pvc:
      name: backup
---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
  name: audio
  namespace: media-files
spec:
  commonConfig: smb-config
  browseable: true
  readOnly: true

  storage:
    pvc:
      name: audio
```
