### ISSUE TITLE
Add sample for OpenShift's DNS operator to resolve AD-Zone

### ISSUE THREAD

**Issue by ibotty** [samba-in-kubernetes/samba-operator#176]
This issue is more of a stopgap until proper documentation is written for people searching for that information.  I intend to write this up properly.

OpenShift's DNS operator does not allow editing the coredns configmap when in managed state.  It does support changing the CRD though.  The following file does the same on OpenShift as the file in [`tests/files/coredns-snippet.template`](https://github.com/samba-in-kubernetes/samba-operator/blob/39b0ebc9158fd447505d21e0be3699b2e4f841bd/tests/files/coredns-snippet.template).
The file can be applied with
```
oc patch dns.operator/default --type merge --patch-file /path/to/file
```

(Of course `AD_SERVER_IP` has to be the actual IP.)

```
spec:
  servers:
  - name: ad-zone
    zones:
    - ad.schaeffer-ag.de
    forwardPlugin:
      upstreams:
      - AD_SERVER_IP
```
