### ISSUE TITLE
samba-operator-controller-manager deployment on openshift has minimal hardcoded ressource limits

### ISSUE THREAD

**Issue by turricum** [samba-in-kubernetes/samba-operator#195]
`oc edit deployment/samba-operator-controller-manager`
 and then:

```

       resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
```
the results are Out of Memory fails. So i changed it manually and it works. The Values are to small ... (0,1 Core and 20M Memory)
