### ISSUE TITLE
Why two CRD types?

### ISSUE THREAD

**Issue by phlogistonjohn** [samba-in-kubernetes/samba-operator#2]
I was trying out this operator and following along with the readme but couldn't figure out the justfication for the two different CRDs. It seems like the SmbPvc is meant to create a SmbService and a PVC and glue them together. If I'm right I'm not quite sure what the advantage is.

If I may, my first thought is that the CRDs should be more oriented toward the task the user (cluster/storage admins) are going to be performing. In that way, SmbService makes some sense but you perhaps even go more granluar and create SmbShare CRDs instead.

IMO if you want to bind the lifecycle of a PV/PVC from a lower part of the storage stack either by name, for an existing PVC, or by directly specifying the pvc parameters I'd go with something like:
```yaml
source:
  pvc:
    name: "mypvcname"
```
AND as an alternate form
```yaml
source:
  pvc:
    spec:
        #...embedded pvc spec...
```
