### ISSUE TITLE
Operator does not reload when SmbShare's settings are changed

### ISSUE THREAD

**Issue by pfaelzerchen** [samba-in-kubernetes/samba-operator#320]
I recognized that the samba-operator seems to automatically resolve changes to SmbShare definitions. I applied to following definition with kubectl apply:

```yaml
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
  name: backup-windows
  namespace: media-files
spec:
  shareName: "backup"
  readOnly: true
  browseable: true
  securityConfig: smb-backup-security
  commonConfig: smb-backup-config

  storage:
    pvc:
      name: backup-windows

  scaling:
    availabilityMode: standard
    minClusterSize: 1
    groupMode: never
```

After I got access, I changed spec.readOnly to false (obviously readOnly for backups was a typo). After kubectl apply the resource to the cluster, nothing happened. I had to manually delete the pod for that share. After that, the operator successfully recreated the pod with the new settings.

This behaviour is reproducible. I had expected that the changes would be applied automatically.
