### ISSUE TITLE
parse_dfs_path_strict: Hostname <hostname> is not ours.

### ISSUE THREAD

**Issue by pfaelzerchen** [samba-in-kubernetes/samba-operator#321]
I am not really sure, if this is something important. When I deploy a SmbShare with the following SmbCommonConfig and access it by IP or Hostname of a cluster node, the pod logs:

```
parse_dfs_path_strict: Hostname <ip> is not ours.
parse_dfs_path_strict: Hostname <hostname> is not ours.
```

As far as I can see, so far everything works fine. Access, file creation, updating something works. But every action is logged with the above entry. So feel free to just close this, if it is negligible.

Great work. samba-operator is a real cool and easy to use solution.

```yaml
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbCommonConfig
metadata:
  name: smb-config
  namespace: smb
spec:
  network:
    publish: external
```

**Comment by phlogistonjohn** [comment]
Thanks for the information. Can you run `testparm -s` inside one of the samba containers in the pod (by exec'ing in) and, after filtering out any private info, post it? It may help narrow down what exactly triggers that log line. Thanks!

**Comment by pfaelzerchen** [comment]
Sure, here it is:

```
sh-5.2# testparm -s
Load smb config files from /etc/samba/smb.conf
lp_load_ex: changing to config backend registry
Loaded services file OK.
Weak crypto is allowed by GnuTLS (e.g. NTLM as a compatibility fallback)

WARNING: state directory /var/lib/samba should have permissions 0755 for browsing to work

WARNING: cache directory /var/lib/samba should have permissions 0755 for browsing to work

Server role: ROLE_STANDALONE

# Global parameters
[global]
        disable spoolss = Yes
        dos charset = ascii
        load printers = No
        netbios name = BACKUP-WINDOWS
        printcap name = /dev/null
        registry shares = Yes
        smb ports = 445
        fileid:algorithm = fsid
        idmap config * : backend = tdb
        printing = bsd
        vfs objects = fileid


[backup]
        path = /mnt/fff4e089-c89b-4675-8f23-604ab8c4b167
        read only = No
```

netbios name seems to be the name of the SmbShare:

```yaml
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
  name: backup-windows
  namespace: smb
spec:
  shareName: "backup"
  readOnly: false
  browseable: true
  securityConfig: smb-security
  commonConfig: smb-config

  storage:
    pvc:
      name: backup-windows

  scaling:
    availabilityMode: standard
    minClusterSize: 1
    groupMode: never
```
